import {StyleSheet} from 'react-native';
import {width, height, size, fontSize} from 'react-native-responsive-sizes';
export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#5B61B9',
  },
  header: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',

    width: '100%',
    height: height(5),
    top: height(2),
  },

  headerText: {
    alignSelf: 'center',
    textAlign: 'center',
    color: 'white',
    fontSize: fontSize(23),
    fontWeight: 'bold',
  },
  next: {
    position: 'absolute',
    right: width(5),
    width: width(19),
    maxHeight: 100,
    maxWidth: 100,
    height: width(19),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: size(1000),
    backgroundColor: '#343875',
    opacity: 0.8,
  },
  nextText: {
    color: 'white',
    fontSize: fontSize(17),
  },
  body: {
    position: 'absolute',
    width: '100%',
    height: height(20),
    top: height(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    width: width(90),
    height: height(6),
    color: 'white',

    borderColor: 'white',
    borderRadius: size(10),
    paddingLeft: width(5),
    fontSize: fontSize(14),
    marginBottom: height(5),
  },
  bottom: {
    position: 'absolute',
    width: '100%',
    height: height(8),
    top: height(70),

    alignItems: 'center',
    justifyContent: 'center',
  },
  forgotButton: {
    position: 'absolute',
    left: width(5),
  },
  forgotText: {
    color: 'white',
    fontSize: fontSize(12),
  },
  borderMail: {
    borderBottomWidth: 1,
    borderBottomColor: 'white',

    zIndex: 1,
  },
  desc: {
    position: 'absolute',
    top: height(15),
    color: 'white',
    fontSize: fontSize(11),
    fontWeight: '400',
    width: width(90),
    textAlign: 'left',
  },
  datePickerTouchable: {
    width: width(90),
    height: height(5),
    paddingLeft: width(5),
    borderRadius: size(10),
    justifyContent: 'center',

    marginBottom: height(3),
  },
  datePicker: {
    color: 'white',
    fontSize: fontSize(11),
  },
  genderTouchable: {
    position: 'absolute',
    width: width(90),
    height: height(5),
    top: height(13),
    paddingLeft: width(5),
    borderRadius: size(10),
    justifyContent: 'center',
  },
  addAPhoto: {
    position: 'absolute',
    top: height(-10),
    color: 'white',
    fontSize: fontSize(24),
    fontWeight: 'bold',
  },
  photoContainer: {
    position: 'absolute',
    width: width(50),
    height: width(50),
    top: height(-3),
    borderRadius: size(1000),
    backgroundColor: '#343875',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photo: {
    width: width(50),
    height: width(50),
    borderRadius: size(1000),
    resizeMode: 'contain',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoText: {
    color: '#343875',
    fontSize: fontSize(24),
    fontWeight: 'bold',
  },
  addPhotoButton: {
    position: 'absolute',
    width: width(10),
    height: width(10),
    bottom: height(0),
    right: width(0),
    borderRadius: size(1000),
    backgroundColor: '#80ed99',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chooseCameraContainer: {
    position: 'absolute',
    width: width(50),
    height: height(5),
    left: width(20),
    top: height(23),
    borderRadius: size(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chooseCameraButton: {
    width: width(25),
    height: height(4),
    borderRadius: size(10),
    marginHorizontal: width(1),
    backgroundColor: '#80ed99',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chooseCameraText: {
    color: 'white',
    fontSize: fontSize(11),
  },
});
