import {StyleSheet} from 'react-native';
import {fontSize, height, size, width} from 'react-native-responsive-sizes';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#06101b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    position: 'absolute',
    width: '100%',
    height: height(7),
    justifyContent: 'center',
    alignItems: 'center',
    top: 0,
  },
  headerTitle: {
    fontSize: fontSize(15),
    color: 'white',
    fontWeight: '500',
  },
  searchContainer: {
    width: '100%',
    height: height(7),
    position: 'absolute',
    top: height(7),
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatContainer: {
    width: '100%',
    height: height(70),
    position: 'absolute',
    top: height(18),
    zIndex: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileImage: {
    width: width(40),
    height: width(40),
    borderRadius: size(210),
  },
  imageContainer: {
    width: width(50),
    height: width(50),

    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  chatHeader: {
    position: 'absolute',
    width: '100%',
    height: height(6),

    justifyContent: 'center',
    alignItems: 'center',
    top: 0,
  },
  thumbNail: {
    width: width(8.5),
    height: width(8.5),
    position: 'absolute',
    left: width(12),
    borderRadius: size(210),
  },
  thumbName: {
    position: 'absolute',
    left: width(23),
    color: 'white',
    fontSize: fontSize(11),
  },
  typeMessageContainer: {
    width: '100%',
    height: height(8),
    position: 'absolute',
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatBallon: {
    width: '60%',
    height: height(3),
    backgroundColor: '#f2f2f2',
    position: 'absolute',
    top: height(7),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: size(5),
    opacity: 0.5,
  },
  chatBallonText: {
    color: 'black',
    fontWeight: '500',
    fontSize: fontSize(8),
    textAlign: 'center',
  },
  messageInput: {
    width: width(85),
    height: height(5),
    backgroundColor: 'white',
    borderRadius: size(15),
    marginLeft: size(5),
    paddingLeft: size(35),
  },
  sendButton: {
    position: 'absolute',
    right: width(2),
    backgroundColor: 'white',
    width: width(10),
    height: height(5),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: size(15),
  },
  chatItem: {
    width: '100%',
    height: height(8),
    borderBottomWidth: size(0.3),
    borderBottomColor: 'grey',
    backgroundColor: '#06101b',
    padding: size(10),
    zIndex: 3,
  },
  chatItemText: {
    color: 'white',
    fontSize: fontSize(12),
  },

  chatItemImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
  },
  chatItemPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
    backgroundColor: 'gray',
    justifyContent: 'center',
    alignItems: 'center',
  },

  messageContainer: {
    padding: 10,
    borderRadius: 5,
    marginVertical: 5,
    maxWidth: '80%',
  },
  myMessage: {
    backgroundColor: '#blue',
    alignSelf: 'flex-end',
  },
  theirMessage: {
    backgroundColor: '#green',
    alignSelf: 'flex-start',
  },
  inputContainer: {
    flexDirection: 'row',
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: '#ddd',
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: size(0.3),
    borderBottomColor: 'grey',
    padding: size(10),
    zIndex: 3,
  },
  headerContainer: {
    width: '100%',
    height: height(7),
    position: 'absolute',
    top: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    color: 'white',
    fontSize: fontSize(15),
    position: 'absolute',
    top: size(10),
  },
  avatar: {
    width: width(12),
    height: width(12),
    borderRadius: size(210),
  },
  avatarPlaceholder: {
    width: width(10),
    height: width(10),
    borderRadius: size(210),
    backgroundColor: 'gray',
    justifyContent: 'center',
    alignItems: 'center',
  },
  userText: {
    position: 'absolute',
    left: width(15),
    top: size(5),
    color: 'white',
    fontSize: fontSize(13),
    marginLeft: size(10),
  },
  lastMessage: {
    position: 'absolute',
    left: width(15),
    top: size(40),
    color: 'grey',
    fontSize: fontSize(10),
    marginLeft: size(10),
  },
});
