import {StyleSheet} from 'react-native';
import {height, size, width} from 'react-native-responsive-sizes';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#06101b',
    width: '100%',
  },
  logo: {
    width: 120,
    height: 120,
    objectFit: 'contain',
  },
  searchContainer: {
    position: 'absolute',
    width: width(100),
    height: width(11),
    top: size(10),
    borderBottomWidth: size(0.3),
    borderBottomColor: 'grey',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchInput: {
    width: width(98),
    height: width(8),
    fontSize: size(12),
    padding: size(10),
    paddingLeft: size(40),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#535355',
    color: 'white',
    borderRadius: size(20),
  },
  searcIcon: {
    position: 'absolute',
    left: size(15),
    zIndex: 1,
  },
  filterContainer: {
    width: width(100),
    height: width(11),
    top: size(55),
    borderBottomWidth: size(0.3),
    borderBottomColor: 'grey',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
  },
  filterText: {
    color: 'white',
    fontSize: size(13),
    textAlign: 'center',
    position: 'absolute',
    zIndex: 1,
    left: size(45),
  },
  body: {
    width: width(100),
    height: height(69),
    top: size(45),
  },
  header: {
    width: width(100),
    height: height(3),
    flexDirection: 'row',
    zIndex: 1,
  },
  headerText: {
    color: 'grey',
    fontSize: size(10),
    fontWeight: 'bold',
    textAlign: 'center',
    position: 'absolute',
    zIndex: 1,
    left: size(15),
  },
});
